### ISSUE TITLE
Can’t install

### ISSUE THREAD

**Issue by bradlc** [dewsign/nova-repeater-blocks#10]
Hey 👋

I can’t seem to install your package on a fresh Nova installation (v1.1.7). Here’s the error:

```
$ composer require dewsign/nova-repeater-blocks
Using version ^1.0 for dewsign/nova-repeater-blocks
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dewsign/nova-repeater-blocks v1.0.4 requires laravel/nova ^1.1 -> no matching package found.
    - dewsign/nova-repeater-blocks v1.0.3 requires laravel/nova ^1.1 -> no matching package found.
    - dewsign/nova-repeater-blocks v1.0.2 requires laravel/nova ^1.1 -> no matching package found.
    - dewsign/nova-repeater-blocks v1.0.1 requires laravel/nova ^1.1 -> no matching package found.
    - Installation request for dewsign/nova-repeater-blocks ^1.0 -> satisfiable by dewsign/nova-repeater-blocks[v1.0.1, v1.0.2, v1.0.3, v1.0.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

This is a completely new Nova installation, installed using the steps from the [Nova docs](https://nova.laravel.com/docs/1.0/installation.html#installing-nova).

Thanks!

**Comment by m2de** [comment]
Hi. Thanks for the head-up. As it happens, this package probably is currently awaiting some third-party package updates but we are yet to hear from the maintainers. Whilst this isn't related to your issue, just thought I'd mention it.

I believe the issue is that we typically pull in Nova from a versioned private repository and I hadn't considered that the official file-based installation doesn't use composer versioning.

You are welcome to submit a PR to change the composer required version to "*" or alternatively I'd suggest to use the composer installation method which should just work. We will certainly address this in the next release.

Cheers.

**Comment by bradlc** [comment]
Thanks for your response @m2de! Got it working after installing Nova via composer.

**Comment by m2de** [comment]
Excellent, thanks for confirming.
